entryWidth =3.453;
conesZ0 = 0;

entryConesLoc = [entryWidth/2 -12;...
                 -entryWidth/2 -12;...
                 -entryWidth/2 -10;...
                 entryWidth/2 -10];

entryConesLoc= fliplr(entryConesLoc); % account for game engine coords

rightInnerRingLoc = [entryWidth/2 0;...%1
                  4.58/2 -2.834;...%2
                  7.787/2 -5.231;...%3
                  12.588/2 -6.835;...%4
                  18.25/2 -7.398;...%5
                  23.912/2 -6.835;...%6
                  28.713/2 -5.231;...%7
                  31.92/2 -2.834;...%8
                  33.047/2 0;...%9
                  31.92/2 2.834;...%10
                  28.713/2 5.231;...%11
                  23.912/2 6.835;...%12
                  18.25/2 7.398;...%13
                  12.588/2 6.835;...%14
                  7.787/2 5.231;...%15
                  4.58/2 2.834;...%16    
                  ];

rightOuterRingLoc = [entryWidth/2 7.939;...% right side entry to exit zone
                      9.945/2 10.026;...
                      18.25/2 10.852;...
                      26.555/2 10.026;...
                      33.596/2 7.673;...
                      38.301/2 4.153;...
                      39.953/2 0;...
                      38.301/2 -4.153;...
                      33.596/2 -7.673;...
                      26.555/2 -10.026;...
                      18.25/2 -10.852;...
                      9.945/2 -10.026;...                      
                      entryWidth/2 -7.939;...% right side after entry zone                      
                      ];

rightInnerRingLoc = fliplr(rightInnerRingLoc);
rightOuterRingLoc = fliplr(rightOuterRingLoc);

leftInnerRingLoc = rightInnerRingLoc.*[1 -1];
leftOuterRingLoc = rightOuterRingLoc.*[1 -1];

exitConesLoc = [entryWidth/2 16;...
                 -entryWidth/2 16;...
                 entryWidth/2-1 16;...
                 -entryWidth/2+1 16;...
                 -entryWidth/2 14;...
                 entryWidth/2 14;...
                 -entryWidth/2 12;...
                 entryWidth/2 12;...
                 -entryWidth/2 10;...
                 entryWidth/2 10];
exitConesLoc= fliplr(exitConesLoc); % account for game engine coords

timeConesLoc = [entryWidth/2 .5;...
                 -entryWidth/2 .5;...
                 entryWidth/2 -.5;...
                 -entryWidth/2 -.5];
timeConesLoc = fliplr(timeConesLoc);

blueCones = [rightOuterRingLoc; leftInnerRingLoc];
yellowCones = [rightInnerRingLoc; leftOuterRingLoc];
smallOrangeCones = [entryConesLoc; exitConesLoc];
largeOrangeCones = timeConesLoc;

% skidSurface = sim3d.Actor('ActorName','BaseSurface');
% createShape(skidSurface, 'box', [45,45,+0.03]);
% skidSurface.Color = [68 68 71]./100;
% skidSurface.Translation = [0 0 0]; 
% skidSurface.Texture = fullfile(pwd,"vdynskidpad.png"); 
% skidSurface.TextureTransform.Scale = [1 1];
% skidSurface.TextureTransform.Angle = 0;
% skidSurface.Shininess = 0;
% skidSurface.Transparency = 0;
% skidSurface.TextureMapping.Blend = 1;
% skidSurface.TextureMapping.Roughness = .8;
% 
% World.add(skidSurface,Actor);

nCones = length(largeOrangeCones);
for coneNum = 1:nCones
    coneName = "LCone_" + num2str(coneNum);
    conLoc = [largeOrangeCones(coneNum,:) conesZ0];
    cone = sim3d.Actor('ActorName',coneName,...
        'Mesh','/Game/Environment/Industrial/Props/Cone/Mesh/SM_Cone.SM_Cone',...
        'Mobility', sim3d.utils.MobilityTypes.Movable,...
        'SimulatePhysics', true,...
        'Translation',conLoc,...
        'EnableGravity', true);
    World.add(cone,Actor);
end

for coneNum = 1:length(blueCones)    
    coneName = "bCone_" + num2str(coneNum);
    conLoc = [blueCones(coneNum,:) conesZ0];
    cone = sim3d.Actor('ActorName',coneName,...
        'Mesh','/Game/Environment/Industrial/Props/Cone/Mesh/SM_Cone_Blue.SM_Cone_Blue',...
        'Mobility', sim3d.utils.MobilityTypes.Movable,...
        'SimulatePhysics', true,...
        'Translation',conLoc,...
        'EnableGravity', true,...
        'Scale',ones(1,3).*325/500);    
    World.add(cone,Actor);
end
for coneNum = 1:length(yellowCones)    
    coneName = "yCone_" + num2str(coneNum);
    conLoc = [yellowCones(coneNum,:) conesZ0];
    cone = sim3d.Actor('ActorName',coneName,...
        'Mesh','/Game/Environment/Industrial/Props/Cone/Mesh/SM_Cone_Yellow.SM_Cone_Yellow',...
        'Mobility', sim3d.utils.MobilityTypes.Movable,...
        'SimulatePhysics', true,...
        'Translation',conLoc,...
        'EnableGravity', true,...
        'Scale',ones(1,3).*325/500);    
    World.add(cone,Actor);
end
for coneNum = 1:length(smallOrangeCones)    
    coneName = "sCone_" + num2str(coneNum);
    conLoc = [smallOrangeCones(coneNum,:) conesZ0];
    cone = sim3d.Actor('ActorName',coneName,...
        'Mesh','/Game/Environment/Industrial/Props/Cone/Mesh/SM_Cone.SM_Cone',...
        'Mobility', sim3d.utils.MobilityTypes.Movable,...
        'SimulatePhysics', true,...
        'Translation',conLoc,...
        'EnableGravity', true,...
        'Scale',ones(1,3).*325/500);    
    World.add(cone,Actor);
end

%Copyright 2023 The MathWorks, Inc.