function [V]=calcul_vitessesrouesretour(Vx,Vy,psipoint,d_f,d_r,l_f,l_r)
Vx1=Vx-d_f/2*psipoint;
Vy1=Vy+l_f*psipoint;
Vx2=Vx+d_f/2*psipoint;
Vy2=Vy+l_f*psipoint;
Vx3=Vx-d_r/2*psipoint;
Vy3=Vy-l_r*psipoint;
Vx4=Vx+d_r/2*psipoint;
Vy4=Vy-l_r*psipoint;
V=[Vx1 Vy1 Vx2 Vy2 Vx3 Vy3 Vx4 Vy4];